# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnorm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_posteriorAdjustment_dmvnorm_arma`, x, mean, sigma, logd)
}

dconditional_arma <- function(x, sigma, nugget, logd = TRUE, na_rm = TRUE) {
    .Call(`_posteriorAdjustment_dconditional_arma`, x, sigma, nugget, logd, na_rm)
}

dconditional_arma2 <- function(x, A, B, sigma0, nugget, logd = TRUE, na_rm = TRUE) {
    .Call(`_posteriorAdjustment_dconditional_arma2`, x, A, B, sigma0, nugget, logd, na_rm)
}
