# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the probability density function of a multivariate Gaussian
#' using the Rcpparmadillo package.
#' Here, x is a (d x n)-dimensional matrix, consisting of n d-dimensional random variables,
#' mean is a d-dimensional vector,
#' sigma is a (d x d)-dimensional covariance matrix,
#' and logd is a bool, stating whether we want the log-density or not.
dmvnorm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_posteriorAdjustment_dmvnorm_arma`, x, mean, sigma, logd)
}

dconditional_arma <- function(x, A, B, sigma0, nugget, logd = TRUE, na_rm = TRUE) {
    .Call(`_posteriorAdjustment_dconditional_arma`, x, A, B, sigma0, nugget, logd, na_rm)
}

